### ISSUE TITLE
数据集网盘权限

### ISSUE THREAD

**Issue by zhanghaok** [tricktreat/piqn#1]
![image](https://user-images.githubusercontent.com/39120036/159664528-fd76380f-d330-498a-b048-017326dba794.png)
老师你好，刚发现数据集网盘还有权限，能否开一下呢

**Comment by tricktreat** [comment]
抱歉没注意权限，现在可以了吧？

**Comment by zhanghaok** [comment]
> 抱歉没注意权限，现在可以了吧？
嘿嘿，可以啦！谢谢老师！！！
