### ISSUE TITLE
OntoNotes 5.0 Version

### ISSUE THREAD

**Issue by addiu** [tricktreat/piqn#3]
Dear authors,
thanks a lot for the nice work and the git repository.

I have the access of the original/raw OnotoNotes 5.0 data, yet I am not clear how the preprocessing has been done on your side.

1) Your repository offers this [link](https://github.com/yhcc/OntoNotes-5.0-NER) for preprocessing; it is mentioned that there are two versions: v4 and v12. May I know which one are you using?
2) According to the paper, it seems that you neither use v4 nor v12. Instead, you seem to use the `flat` version of OntoNotes 5.0. If so, may I know the reason for that? Also, I don't know how to access the flat version of the OntoNotes 5.0 dataset, even on their official [repository](https://github.com/ShannonAI/mrc-for-flat-nested-ner).
3) In general,  do you know which OntoNotes version we should use? v4, v12 or flat? 

Thanks a lot!

**Comment by tricktreat** [comment]
Hi, we used the v4 version. In the study of named entity recognition, v4 version is more general. Also, regardless of v4 or v12, OntoNotes 5.0 dataset has only flat named entities.

**Comment by addiu** [comment]
Hi, 
thanks a lot for the quick clarification!
