### ISSUE TITLE
对论文中的公式有些困惑

### ISSUE THREAD

**Issue by T00ler** [tricktreat/piqn#9]
![VW(7CWPATSP`ETGM1{S_LU4](https://github.com/tricktreat/piqn/assets/57865092/5a801566-8ed6-4f72-8776-48f7009338d2)
您好，想请教一下论文里的公式。论文中Sti，即“The boundary-aware representation”由三个size为1*h的向量concatenate得到，那就是3*h的size。可下面的公式计算使用Sti乘了一个1*h的权重矩阵加偏置，最后不应该得到一个(3,)的向量吗，但看样子这里应该得到的是一个数字才对。

**Comment by tricktreat** [comment]
感谢指出。这里的W_t^c应该是R^{3h}。
